#!/bin/zsh

# Install Homebrew
if ! command -v brew &> /dev/null
then
	echo "Installing Homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install asdf-vm
if ! command -v asdf &> /dev/null
then
	echo "Installing asdf-vm..."
	git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
fi

# Files to symlink
Brewfile=~/Brewfile
zsh=~/.zshrc
vim=~/.vimrc
nvim_init=~/.config/nvim/init.lua
nvim_utils=~/.config/nvim/lua/utils.lua
ripgrep=~/.ignore
ranger=~/.config/ranger/rc.conf
bat=~/.config/bat/config
hammerspoon=~/.hammerspoon/init.lua
kitty=~/.config/kitty/kitty.conf

# Homebrew
if [ ! -L $Brewfile ] ; then
	echo "Creating symbolic link for Brewfile..."
	ln -s $PWD/homebrew/Brewfile $Brewfile
fi

echo "Installing Brewfile packages..."
brew bundle --file=$Brewfile

# ZSH
if [ ! -L $zsh ] ; then
	echo "Creating symbolic link for .zshrc..."
	ln -s $PWD/zsh/zshrc $zsh
fi

# Vim
if [ ! -L $vim ] ; then
	echo "Creating symbolic link for .vimrc..."
	ln -s $PWD/vim/vimrc $vim
fi

# Neovim
if [ ! -L $nvim_init ] ; then
	echo "Creating symbolic link for nvim/init.lua..."
	mkdir -p ~/.config/nvim
	ln -s $PWD/neovim/init.lua $nvim_init
fi

if [ ! -L $nvim_utils ] ; then
	echo "Creating symbolic link for nvim/lua/utils.lua..."
	mkdir -p ~/.config/nvim/lua
	ln -s $PWD/neovim/utils.lua $nvim_utils
fi

if [ ! -L $ripgrep ] ; then
	echo "Adding .ignore for ripgrep..."
	ln -s $PWD/ripgrep/ignore $ripgrep
fi

# Ranger
if [ ! -L $ranger ] ; then
	echo "Creating symbolic link for Ranger config..."
	ln -s $PWD/ranger/rc.conf $ranger
fi

# BAT
if [ ! -L $bat ] ; then
	echo "Creating symbolic link for BAT config..."
	ln -s $PWD/bat/config $bat
fi

# Hammerspoon
if [ ! -L $hammerspoon ] ; then
	echo "Creating symbolic link for Hammerspoon config..."
	ln -s $PWD/hammerspoon/init.lua $hammerspoon
fi

# Kitty
if [ ! -L $kitty ] ; then
	echo "Creating symbolic link for Kitty config..."
	mkdir -p ~/.config/kitty
	ln -s $PWD/kitty/kitty.conf $kitty
fi
