syntax on

" Vim Plug
call plug#begin('~/.vim/plugged')

Plug 'gruvbox-community/gruvbox'
Plug 'sheerun/vim-polyglot'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'francoiscabrol/ranger.vim'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'

call plug#end()

" The best colorscheme
colorscheme gruvbox

" Relative line numbering
set number relativenumber

" Scrolling preferences
set mouse=a
set scrolloff=8

" Highlight current line when inserting
autocmd InsertEnter,InsertLeave * set cul!

" Set characters for tab indentation and trailing whitespace
set list
set listchars=trail:·,tab:>-
hi SpecialKey ctermfg=59 guifg=#5f5f5f

" Statusline customization
set laststatus=2
set statusline=
set statusline+=\ %f
set statusline+=%=
set statusline+=\ %p%%
set statusline+=\ %l:%c
set statusline+=\ %y

" Buffer interactions
nnoremap <silent> <C-b> :buffers<CR>

" Exploring File Tree
nnoremap <silent> <C-e> :Ranger<CR>
let g:ranger_map_keys = 0
let g:ranger_replace_netrw = 1

" Searching For Files
nnoremap <silent> <C-p> :Files<CR>
let g:fzf_layout = { 'window': { 'width': 0.8, 'height': 0.8 } }
let g:fzf_preview_window = 'right:62%'
let $FZF_DEFAULT_OPTS='--reverse'

" Searching In Files
nnoremap <silent> <C-f> :Rg<CR>
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, {'options': '--delimiter : --nth 4..'}, <bang>0)
set grepprg=rg\ --vimgrep\ --smart-case\ --follow

" Cache and buffer stuff I don't fully understand
set hidden
set noswapfile
set nobackup
set nowritebackup
set updatetime=50

" Search preferences
set incsearch
set nohlsearch

" Turn off annoying error bells
set noerrorbells
set belloff=all

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Always show signcolumn with transparent background
set signcolumn=yes
highlight clear SignColumn
highlight GitGutterAdd          ctermfg=142
highlight GitGutterChange       ctermfg=214
highlight GitGutterDelete       ctermfg=167
highlight GitGutterChangeDelete ctermfg=208
highlight GruvboxRedSign        ctermfg=167 ctermbg=NONE
highlight GruvboxGreenSign      ctermfg=142 ctermbg=NONE
highlight GruvboxYellowSign     ctermfg=214 ctermbg=NONE
highlight GruvboxBlueSign       ctermfg=109 ctermbg=NONE
highlight GruvboxPurpleSign     ctermfg=175 ctermbg=NONE
highlight GruvboxAquaSign       ctermfg=108 ctermbg=NONE
highlight GruvboxOrangeSign     ctermfg=208 ctermbg=NONE

" Go Settings
autocmd FileType go setlocal noexpandtab tabstop=8

" Rust Settings
let g:rust_clip_command = 'pbcopy'
