# asdf Erlang dependencies
brew "openssl"
brew "autoconf"
brew "wxmac"

# asdf NodeJS dependencies
brew "coreutils"
brew "gpg"

# Vim dependencies
brew "vim"
brew "fzf"
brew "ripgrep"
brew "ranger"

# CLIs
brew "exercism"

# Miscellaneous goodies
brew "bat"
brew "glow"

# Casks
cask "hammerspoon"
cask "keycastr"

