export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# Amend an old commit using the hash as an argument
gfix() {
  git commit --fixup="$1"
  git rebase --interactive --autosquash "$1"\^
}

# Get installed vscode extensions
alias vscode-extensions="code --list-extensions | xargs -L 1 echo code --install-extension"

# Set up asdf version manager
. $HOME/.asdf/asdf.sh

fpath=(${ASDF_DIR}/completions $fpath)
autoload -Uz compinit
compinit

# Use FZF for search
export FZF_DEFAULT_COMMAND="rg -l --hidden --iglob '!.git' ''"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Import system-specific config
source ~/.profile

# Run neofetch if it's installed
if type "$neofetch" > /dev/null; then
  neofetch
fi
