export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# Amend an old commit using the hash as an argument
gfix() {
  git commit --fixup="$1"
  git rebase --interactive --autosquash "$1"\^
}

# Get installed vscode extensions
alias vscode-extensions="code --list-extensions | xargs -L 1 echo code --install-extension"

# Set up asdf version manager
. $HOME/.asdf/asdf.sh

fpath=(${ASDF_DIR}/completions $fpath)
autoload -Uz compinit
compinit

# Use FZF for search
iglobs=""                   # Globs to pass to default fzf rg command
iglobs+=" --iglob '!.git'"  # Ignore *.git files in files search
iglobs+=" --iglob '!.beam'" # Ignore *.beam files in files search

export FZF_DEFAULT_COMMAND="rg --files --hidden $iglobs"
export FZF_DEFAULT_OPTS='-m --height 50% --border'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Use neovim as default editor
 export VISUAL=vim;
 export EDITOR=vim;

# Import system-specific config
source ~/.profile
